version: '3.7'

services:
  database:
    image: postgres:11.5-alpine
    container_name: ${DB_CONTAINER_NAME}
    volumes:
      - postgres_data:/var/lib/potgresql/data/
    ports:
      #      Local development only
      - ${DATABASE_EXPOSE_PORT}:5432

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: ${PROJECT_CONTAINER_NAME}
    command: sh /scripts/start-backend.sh
    volumes:
      - ./backend/project_backend/:/${PROJECT_WORK_DIR}
      - .env:/${PROJECT_WORK_DIR}/.env
    ports:
      - ${WSGI_PORT}:${WSGI_PORT}
    depends_on:
      - database

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    container_name: project_frontend
#    command: yarn && yarn build && yarn start
    command: sh /scripts/start-frontend.sh
    volumes:
      - ./frontend/project_frontend:/frontend
    ports:
      - "${FE_EXTERNAL_PORT}:${FE_INTERNAL_PORT}"
    environment:
      HOST: ${FE_HOST}

volumes:
  postgres_data:
