version: '3.7'

services:
  database:
    image: postgres:11.5-alpine
    container_name: ${DB_CONTAINER_NAME}
    volumes:
      - postgres_data:/var/lib/potgresql/data/
    ports:
      #      Local development only
      - ${DATABASE_EXPOSE_PORT}:5432

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: ${PROJECT_CONTAINER_NAME}
    command: sh /scripts/start-backend.sh
    volumes:
      - ./backend/project_backend/:/${PROJECT_WORK_DIR}
      - .env:/${PROJECT_WORK_DIR}/.env
    ports:
      - ${WSGI_PORT}:${WSGI_PORT}
    environment:
      - PYTHONDONTWRITEBYTECODE:1
    depends_on:
      - database

volumes:
  postgres_data:
